version: '3.2'
services:
  # start service for redmine with plugin
  # 1. $ docker-compose build --force-rm --no-cache
  # 2. $ docker-compose up -d web
  #
  #
  web:
    build:
      context: .
    container_name: redmine_theme_kodomo_midori
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app/redmine/public/themes/redmine_theme_kodomo_midori
      - ./.data:/app/data
    ports:
      - "3000:3000"
