name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: akiko/redmine_theme_kodomo_midori
          tags: latest
      # - name: Login to Heroku Container registry
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #   run: heroku container:login
      # - name: Build and push
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #   run: |
      #     docker tag akiko/redmine_theme_kodomo_midori:latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      #     docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      # - name: Release
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #   run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
